function J = localJac(R, c1, c2, e1, e2)
    x = R(1);
    y = R(2);

    idx1x = e1(:,1) > 0;  % for df1/dx
    idx1y = e1(:,2) > 0;  % for df1/dy
    idx2x = e2(:,1) > 0;  % for df2/dx
    idx2y = e2(:,2) > 0;  % for df2/dy

    % df1/dx
    df1dx = sum( ...
        c1(idx1x) .* ...
        e1(idx1x,1) .* ...
        x.^(e1(idx1x,1) - 1) .* ...
        y.^ e1(idx1x,2) );

    % df1/dy
    df1dy = sum( ...
        c1(idx1y) .* ...
        e1(idx1y,2) .* ...
        x.^ e1(idx1y,1) .* ...
        y.^(e1(idx1y,2) - 1) );

    % df2/dx
    df2dx = sum( ...
        c2(idx2x) .* ...
        e2(idx2x,1) .* ...
        x.^(e2(idx2x,1) - 1) .* ...
        y.^ e2(idx2x,2) );

    % df2/dy
    df2dy = sum( ...
        c2(idx2y) .* ...
        e2(idx2y,2) .* ...
        x.^ e2(idx2y,1) .* ...
        y.^(e2(idx2y,2) - 1) );

    J = [df1dx, df1dy;
         df2dx, df2dy];
end